mutation CreateRichPod($input: CreateRichPodInput!) {
    createRichPod(input: $input) {
        ...RichPodFields
        origin {
            id
            title
            link
            feedUrl
            artworkUrl
            verified
            episode {
                guid
                title
                artworkUrl
                link
                media {
                    url
                    type
                    length
                    checksum
                }
            }
        }
        chapters {
            ...ChapterFields
        }
    }
}

mutation UpdateRichPod($id: ID!, $sessionId: String!, $input: UpdateRichPodInput!) {
    updateRichPod(id: $id, sessionId: $sessionId, input: $input) {
        ...RichPodFields
        origin {
            id
            title
            link
            feedUrl
            artworkUrl
            verified
            episode {
                guid
                title
                artworkUrl
                link
                media {
                    url
                    type
                    length
                    checksum
                }
            }
        }
        chapters {
            ...ChapterFields
        }
    }
}

mutation DeleteRichPod($id: ID!) {
    deleteRichPod(id: $id)
}

mutation SetRichPodChapters($id: ID!, $sessionId: String!, $chapters: [ChapterInput!]!) {
    setRichPodChapters(id: $id, sessionId: $sessionId, chapters: $chapters) {
        ...RichPodFields
        origin {
            id
            title
            link
            feedUrl
            artworkUrl
            verified
            episode {
                guid
                title
                artworkUrl
                link
                media {
                    url
                    type
                    length
                    checksum
                }
            }
        }
        chapters {
            ...ChapterFields
        }
    }
}

query GetRichPod($id: ID!) {
    richPod(id: $id) {
        ...RichPodFields
        origin {
            id
            title
            link
            feedUrl
            artworkUrl
            verified
            episode {
                guid
                title
                artworkUrl
                link
                media {
                    url
                    type
                    length
                    checksum
                }
            }
        }
        chapters {
            ...ChapterFields
        }
    }
}

mutation RefreshEpisodeMedia($richPodId: ID!) {
    refreshEpisodeMedia(richPodId: $richPodId) {
        url
        type
        length
        checksum
    }
}

mutation GenerateAiChapters($richPodId: ID!, $sessionId: String!) {
    generateAiChapters(richPodId: $richPodId, sessionId: $sessionId) {
        ...ChapterGenerationStatusFields
    }
}

mutation RecordChapterGenerationBaseline($richPodId: ID!, $sessionId: String!) {
    recordChapterGenerationBaseline(richPodId: $richPodId, sessionId: $sessionId) {
        ...ChapterGenerationStatusFields
    }
}

mutation GenerateTranscript($richPodId: ID!, $sessionId: String!) {
    generateTranscript(richPodId: $richPodId, sessionId: $sessionId) {
        ...ChapterGenerationStatusFields
    }
}

query ChapterGenerationStatus($richPodId: ID!) {
    chapterGenerationStatus(richPodId: $richPodId) {
        ...ChapterGenerationStatusFields
    }
}

query TranscriptGenerationStatus($richPodId: ID!) {
    transcriptGenerationStatus(richPodId: $richPodId) {
        ...ChapterGenerationStatusFields
    }
}

query RichPodTranscript($richPodId: ID!) {
    richPodTranscript(richPodId: $richPodId) {
        ...TranscriptFields
    }
}
